/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 brain.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/brain.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.brain.geometry} material={materials.brain} rotation={[Math.PI / 2, 0, 0]} scale={3} />
    </group>
  )
}

useGLTF.preload('/brain.gltf')
